export const ERROR_CODES = {
  // Authentication & Security
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  IP_NOT_ALLOWED: 'IP_NOT_ALLOWED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TWO_FACTOR_REQUIRED: 'TWO_FACTOR_REQUIRED',

  // Validation & Input
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_JSON: 'INVALID_JSON',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',

  // CRM Domain Errors
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  CONTACT_ALREADY_EXISTS: 'CONTACT_ALREADY_EXISTS',
  DEAL_NOT_FOUND: 'DEAL_NOT_FOUND',
  INVALID_STAGE_TRANSITION: 'INVALID_STAGE_TRANSITION',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
  TICKET_ALREADY_CLOSED: 'TICKET_ALREADY_CLOSED',
  SLA_POLICY_NOT_FOUND: 'SLA_POLICY_NOT_FOUND',
  PIPELINE_NOT_FOUND: 'PIPELINE_NOT_FOUND',
  LEAD_ALREADY_CONVERTED: 'LEAD_ALREADY_CONVERTED',

  // Omnichannel & Messaging
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CHANNEL_NOT_CONFIGURED: 'CHANNEL_NOT_CONFIGURED',
  WHATSAPP_TEMPLATE_REJECTED: 'WHATSAPP_TEMPLATE_REJECTED',
  EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',

  // Integrations & Webhooks
  INTEGRATION_AUTH_FAILED: 'INTEGRATION_AUTH_FAILED',
  SALESFORCE_SYNC_ERROR: 'SALESFORCE_SYNC_ERROR',
  HUBSPOT_SYNC_ERROR: 'HUBSPOT_SYNC_ERROR',
  WEBHOOK_DELIVERY_FAILED: 'WEBHOOK_DELIVERY_FAILED',

  // System & Internal
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  DATABASE_TIMEOUT: 'DATABASE_TIMEOUT',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
