export const PERMISSIONS = {
  // Contacts
  CONTACTS_READ: 'contacts:read',
  CONTACTS_WRITE: 'contacts:write',
  CONTACTS_DELETE: 'contacts:delete',
  CONTACTS_EXPORT: 'contacts:export',
  CONTACTS_MERGE: 'contacts:merge',

  // Deals
  DEALS_READ: 'deals:read',
  DEALS_WRITE: 'deals:write',
  DEALS_DELETE: 'deals:delete',
  DEALS_MOVE_STAGE: 'deals:move_stage',
  DEALS_FORECAST_VIEW: 'deals:forecast_view',

  // Tickets
  TICKETS_READ: 'tickets:read',
  TICKETS_WRITE: 'tickets:write',
  TICKETS_ASSIGN: 'tickets:assign',
  TICKETS_ESCALATE: 'tickets:escalate',
  TICKETS_CLOSE: 'tickets:close',

  // Omnichannel Conversations
  CONVERSATIONS_READ: 'conversations:read',
  CONVERSATIONS_WRITE: 'conversations:write',
  CONVERSATIONS_ASSIGN: 'conversations:assign',
  CONVERSATIONS_RESOLVE: 'conversations:resolve',

  // Campaigns & Marketing
  CAMPAIGNS_READ: 'campaigns:read',
  CAMPAIGNS_WRITE: 'campaigns:write',
  CAMPAIGNS_SEND: 'campaigns:send',
  SEGMENTS_MANAGE: 'segments:manage',

  // Reports & Analytics
  REPORTS_VIEW: 'reports:view',
  REPORTS_EXPORT: 'reports:export',
  REPORTS_CUSTOM_BUILD: 'reports:custom_build',

  // Integrations & Developer
  API_KEYS_MANAGE: 'api_keys:manage',
  WEBHOOKS_MANAGE: 'webhooks:manage',
  INTEGRATIONS_CONFIG: 'integrations:config',

  // Admin & Compliance
  ORG_SETTINGS_MANAGE: 'org_settings:manage',
  MEMBERS_MANAGE: 'members:manage',
  BILLING_MANAGE: 'billing:manage',
  AUDIT_LOGS_VIEW: 'audit_logs:view',
  GDPR_ERASURE_EXECUTE: 'gdpr_erasure:execute',
  SLA_POLICIES_MANAGE: 'sla_policies:manage',
  CUSTOM_FIELDS_MANAGE: 'custom_fields:manage',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<'OWNER' | 'ADMIN' | 'AGENT' | 'VIEWER', PermissionKey[]> = {
  OWNER: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.CONTACTS_WRITE,
    PERMISSIONS.CONTACTS_DELETE,
    PERMISSIONS.CONTACTS_EXPORT,
    PERMISSIONS.CONTACTS_MERGE,
    PERMISSIONS.DEALS_READ,
    PERMISSIONS.DEALS_WRITE,
    PERMISSIONS.DEALS_MOVE_STAGE,
    PERMISSIONS.DEALS_FORECAST_VIEW,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_WRITE,
    PERMISSIONS.TICKETS_ASSIGN,
    PERMISSIONS.TICKETS_ESCALATE,
    PERMISSIONS.TICKETS_CLOSE,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.CONVERSATIONS_WRITE,
    PERMISSIONS.CONVERSATIONS_ASSIGN,
    PERMISSIONS.CONVERSATIONS_RESOLVE,
    PERMISSIONS.CAMPAIGNS_READ,
    PERMISSIONS.CAMPAIGNS_WRITE,
    PERMISSIONS.CAMPAIGNS_SEND,
    PERMISSIONS.SEGMENTS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.REPORTS_CUSTOM_BUILD,
    PERMISSIONS.API_KEYS_MANAGE,
    PERMISSIONS.WEBHOOKS_MANAGE,
    PERMISSIONS.INTEGRATIONS_CONFIG,
    PERMISSIONS.MEMBERS_MANAGE,
    PERMISSIONS.AUDIT_LOGS_VIEW,
    PERMISSIONS.SLA_POLICIES_MANAGE,
    PERMISSIONS.CUSTOM_FIELDS_MANAGE,
  ],
  AGENT: [
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.CONTACTS_WRITE,
    PERMISSIONS.DEALS_READ,
    PERMISSIONS.DEALS_WRITE,
    PERMISSIONS.DEALS_MOVE_STAGE,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.TICKETS_WRITE,
    PERMISSIONS.TICKETS_ASSIGN,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.CONVERSATIONS_WRITE,
    PERMISSIONS.CONVERSATIONS_RESOLVE,
    PERMISSIONS.REPORTS_VIEW,
  ],
  VIEWER: [
    PERMISSIONS.CONTACTS_READ,
    PERMISSIONS.DEALS_READ,
    PERMISSIONS.TICKETS_READ,
    PERMISSIONS.CONVERSATIONS_READ,
    PERMISSIONS.REPORTS_VIEW,
  ],
};
