export interface MockIvrDialplanEntry {
  dialplanId: string;
  menuName: string;
  inboundDidPattern: string;
  greetingPromptAudioUri: string;
  digitKeyOptions: Array<{ digit: string; action: string; targetQueue?: string; targetSipUri?: string; targetBotWorkflowId?: string }>;
  fallbackTimeoutSeconds: number;
  businessHoursSchedule: string;
  isRecordingMandatory: boolean;
}

export const ENTERPRISE_TELEPHONY_IVR_DIALPLANS: MockIvrDialplanEntry[] = [
  {
    dialplanId: 'dp_tree_0001',
    menuName: 'Global Inbound Tier 1 Auto-Attendant',
    inboundDidPattern: '+18005550001',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_1.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_1@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_1' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0002',
    menuName: 'Global Inbound Tier 2 Auto-Attendant',
    inboundDidPattern: '+18005550002',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_2.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_2@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_2' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0003',
    menuName: 'Global Inbound Tier 3 Auto-Attendant',
    inboundDidPattern: '+18005550003',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_3.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_3@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_3' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0004',
    menuName: 'Global Inbound Tier 4 Auto-Attendant',
    inboundDidPattern: '+18005550004',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_4.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_4@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_4' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0005',
    menuName: 'Global Inbound Tier 5 Auto-Attendant',
    inboundDidPattern: '+18005550005',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_5.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_5@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_5' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0006',
    menuName: 'Global Inbound Tier 6 Auto-Attendant',
    inboundDidPattern: '+18005550006',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_6.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_6@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_6' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0007',
    menuName: 'Global Inbound Tier 7 Auto-Attendant',
    inboundDidPattern: '+18005550007',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_7.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_7@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_7' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0008',
    menuName: 'Global Inbound Tier 8 Auto-Attendant',
    inboundDidPattern: '+18005550008',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_8.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_8@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_8' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0009',
    menuName: 'Global Inbound Tier 9 Auto-Attendant',
    inboundDidPattern: '+18005550009',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_9.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_9@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_9' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0010',
    menuName: 'Global Inbound Tier 10 Auto-Attendant',
    inboundDidPattern: '+18005550010',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_10.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_10@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_10' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0011',
    menuName: 'Global Inbound Tier 11 Auto-Attendant',
    inboundDidPattern: '+18005550011',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_11.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_11@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_11' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0012',
    menuName: 'Global Inbound Tier 12 Auto-Attendant',
    inboundDidPattern: '+18005550012',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_12.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_12@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_12' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0013',
    menuName: 'Global Inbound Tier 13 Auto-Attendant',
    inboundDidPattern: '+18005550013',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_13.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_13@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_13' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0014',
    menuName: 'Global Inbound Tier 14 Auto-Attendant',
    inboundDidPattern: '+18005550014',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_14.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_14@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_14' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0015',
    menuName: 'Global Inbound Tier 15 Auto-Attendant',
    inboundDidPattern: '+18005550015',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_15.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_15@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_15' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0016',
    menuName: 'Global Inbound Tier 16 Auto-Attendant',
    inboundDidPattern: '+18005550016',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_16.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_16@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_16' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0017',
    menuName: 'Global Inbound Tier 17 Auto-Attendant',
    inboundDidPattern: '+18005550017',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_17.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_17@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_17' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0018',
    menuName: 'Global Inbound Tier 18 Auto-Attendant',
    inboundDidPattern: '+18005550018',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_18.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_18@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_18' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0019',
    menuName: 'Global Inbound Tier 19 Auto-Attendant',
    inboundDidPattern: '+18005550019',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_19.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_19@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_19' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0020',
    menuName: 'Global Inbound Tier 20 Auto-Attendant',
    inboundDidPattern: '+18005550020',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_20.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_20@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_20' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0021',
    menuName: 'Global Inbound Tier 21 Auto-Attendant',
    inboundDidPattern: '+18005550021',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_21.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_21@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_21' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0022',
    menuName: 'Global Inbound Tier 22 Auto-Attendant',
    inboundDidPattern: '+18005550022',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_22.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_22@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_22' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0023',
    menuName: 'Global Inbound Tier 23 Auto-Attendant',
    inboundDidPattern: '+18005550023',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_23.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_23@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_23' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0024',
    menuName: 'Global Inbound Tier 24 Auto-Attendant',
    inboundDidPattern: '+18005550024',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_24.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_24@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_24' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0025',
    menuName: 'Global Inbound Tier 25 Auto-Attendant',
    inboundDidPattern: '+18005550025',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_25.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_25@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_25' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0026',
    menuName: 'Global Inbound Tier 26 Auto-Attendant',
    inboundDidPattern: '+18005550026',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_26.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_26@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_26' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0027',
    menuName: 'Global Inbound Tier 27 Auto-Attendant',
    inboundDidPattern: '+18005550027',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_27.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_27@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_27' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0028',
    menuName: 'Global Inbound Tier 28 Auto-Attendant',
    inboundDidPattern: '+18005550028',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_28.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_28@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_28' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0029',
    menuName: 'Global Inbound Tier 29 Auto-Attendant',
    inboundDidPattern: '+18005550029',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_29.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_29@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_29' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0030',
    menuName: 'Global Inbound Tier 30 Auto-Attendant',
    inboundDidPattern: '+18005550030',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_30.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_30@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_30' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0031',
    menuName: 'Global Inbound Tier 31 Auto-Attendant',
    inboundDidPattern: '+18005550031',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_31.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_31@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_31' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0032',
    menuName: 'Global Inbound Tier 32 Auto-Attendant',
    inboundDidPattern: '+18005550032',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_32.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_32@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_32' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0033',
    menuName: 'Global Inbound Tier 33 Auto-Attendant',
    inboundDidPattern: '+18005550033',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_33.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_33@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_33' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0034',
    menuName: 'Global Inbound Tier 34 Auto-Attendant',
    inboundDidPattern: '+18005550034',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_34.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_34@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_34' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0035',
    menuName: 'Global Inbound Tier 35 Auto-Attendant',
    inboundDidPattern: '+18005550035',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_35.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_35@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_35' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0036',
    menuName: 'Global Inbound Tier 36 Auto-Attendant',
    inboundDidPattern: '+18005550036',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_36.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_36@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_36' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0037',
    menuName: 'Global Inbound Tier 37 Auto-Attendant',
    inboundDidPattern: '+18005550037',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_37.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_37@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_37' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0038',
    menuName: 'Global Inbound Tier 38 Auto-Attendant',
    inboundDidPattern: '+18005550038',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_38.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_38@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_38' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0039',
    menuName: 'Global Inbound Tier 39 Auto-Attendant',
    inboundDidPattern: '+18005550039',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_39.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_39@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_39' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0040',
    menuName: 'Global Inbound Tier 40 Auto-Attendant',
    inboundDidPattern: '+18005550040',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_40.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_40@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_40' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0041',
    menuName: 'Global Inbound Tier 41 Auto-Attendant',
    inboundDidPattern: '+18005550041',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_41.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_41@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_41' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0042',
    menuName: 'Global Inbound Tier 42 Auto-Attendant',
    inboundDidPattern: '+18005550042',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_42.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_42@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_42' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0043',
    menuName: 'Global Inbound Tier 43 Auto-Attendant',
    inboundDidPattern: '+18005550043',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_43.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_43@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_43' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0044',
    menuName: 'Global Inbound Tier 44 Auto-Attendant',
    inboundDidPattern: '+18005550044',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_44.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_44@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_44' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0045',
    menuName: 'Global Inbound Tier 45 Auto-Attendant',
    inboundDidPattern: '+18005550045',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_45.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_45@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_45' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0046',
    menuName: 'Global Inbound Tier 46 Auto-Attendant',
    inboundDidPattern: '+18005550046',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_46.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_46@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_46' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0047',
    menuName: 'Global Inbound Tier 47 Auto-Attendant',
    inboundDidPattern: '+18005550047',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_47.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_47@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_47' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0048',
    menuName: 'Global Inbound Tier 48 Auto-Attendant',
    inboundDidPattern: '+18005550048',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_48.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_48@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_48' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0049',
    menuName: 'Global Inbound Tier 49 Auto-Attendant',
    inboundDidPattern: '+18005550049',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_49.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_49@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_49' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0050',
    menuName: 'Global Inbound Tier 50 Auto-Attendant',
    inboundDidPattern: '+18005550050',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_50.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_50@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_50' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0051',
    menuName: 'Global Inbound Tier 51 Auto-Attendant',
    inboundDidPattern: '+18005550051',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_51.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_51@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_51' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0052',
    menuName: 'Global Inbound Tier 52 Auto-Attendant',
    inboundDidPattern: '+18005550052',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_52.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_52@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_52' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0053',
    menuName: 'Global Inbound Tier 53 Auto-Attendant',
    inboundDidPattern: '+18005550053',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_53.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_53@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_53' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0054',
    menuName: 'Global Inbound Tier 54 Auto-Attendant',
    inboundDidPattern: '+18005550054',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_54.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_54@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_54' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0055',
    menuName: 'Global Inbound Tier 55 Auto-Attendant',
    inboundDidPattern: '+18005550055',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_55.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_55@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_55' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0056',
    menuName: 'Global Inbound Tier 56 Auto-Attendant',
    inboundDidPattern: '+18005550056',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_56.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_56@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_56' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0057',
    menuName: 'Global Inbound Tier 57 Auto-Attendant',
    inboundDidPattern: '+18005550057',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_57.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_57@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_57' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0058',
    menuName: 'Global Inbound Tier 58 Auto-Attendant',
    inboundDidPattern: '+18005550058',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_58.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_58@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_58' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0059',
    menuName: 'Global Inbound Tier 59 Auto-Attendant',
    inboundDidPattern: '+18005550059',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_59.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_59@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_59' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0060',
    menuName: 'Global Inbound Tier 60 Auto-Attendant',
    inboundDidPattern: '+18005550060',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_60.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_60@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_60' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0061',
    menuName: 'Global Inbound Tier 61 Auto-Attendant',
    inboundDidPattern: '+18005550061',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_61.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_61@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_61' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0062',
    menuName: 'Global Inbound Tier 62 Auto-Attendant',
    inboundDidPattern: '+18005550062',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_62.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_62@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_62' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0063',
    menuName: 'Global Inbound Tier 63 Auto-Attendant',
    inboundDidPattern: '+18005550063',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_63.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_63@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_63' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0064',
    menuName: 'Global Inbound Tier 64 Auto-Attendant',
    inboundDidPattern: '+18005550064',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_64.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_64@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_64' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0065',
    menuName: 'Global Inbound Tier 65 Auto-Attendant',
    inboundDidPattern: '+18005550065',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_65.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_65@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_65' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0066',
    menuName: 'Global Inbound Tier 66 Auto-Attendant',
    inboundDidPattern: '+18005550066',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_66.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_66@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_66' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0067',
    menuName: 'Global Inbound Tier 67 Auto-Attendant',
    inboundDidPattern: '+18005550067',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_67.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_67@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_67' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0068',
    menuName: 'Global Inbound Tier 68 Auto-Attendant',
    inboundDidPattern: '+18005550068',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_68.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_68@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_68' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0069',
    menuName: 'Global Inbound Tier 69 Auto-Attendant',
    inboundDidPattern: '+18005550069',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_69.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_69@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_69' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0070',
    menuName: 'Global Inbound Tier 70 Auto-Attendant',
    inboundDidPattern: '+18005550070',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_70.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_70@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_70' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0071',
    menuName: 'Global Inbound Tier 71 Auto-Attendant',
    inboundDidPattern: '+18005550071',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_71.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_71@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_71' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0072',
    menuName: 'Global Inbound Tier 72 Auto-Attendant',
    inboundDidPattern: '+18005550072',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_72.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_72@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_72' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0073',
    menuName: 'Global Inbound Tier 73 Auto-Attendant',
    inboundDidPattern: '+18005550073',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_73.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_73@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_73' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0074',
    menuName: 'Global Inbound Tier 74 Auto-Attendant',
    inboundDidPattern: '+18005550074',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_74.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_74@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_74' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0075',
    menuName: 'Global Inbound Tier 75 Auto-Attendant',
    inboundDidPattern: '+18005550075',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_75.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_75@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_75' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0076',
    menuName: 'Global Inbound Tier 76 Auto-Attendant',
    inboundDidPattern: '+18005550076',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_76.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_1' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_76@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_76' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0077',
    menuName: 'Global Inbound Tier 77 Auto-Attendant',
    inboundDidPattern: '+18005550077',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_77.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_2' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_77@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_77' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0078',
    menuName: 'Global Inbound Tier 78 Auto-Attendant',
    inboundDidPattern: '+18005550078',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_78.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_3' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_1' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_78@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_78' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0079',
    menuName: 'Global Inbound Tier 79 Auto-Attendant',
    inboundDidPattern: '+18005550079',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_79.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_4' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_2' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_79@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_79' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
  {
    dialplanId: 'dp_tree_0080',
    menuName: 'Global Inbound Tier 80 Auto-Attendant',
    inboundDidPattern: '+18005550080',
    greetingPromptAudioUri: 's3://easychat-ivr-prompts/en/prompt_welcome_80.wav',
    digitKeyOptions: [
      { digit: '1', action: 'ROUTE_QUEUE', targetQueue: 'SALES_VIP_0' },
      { digit: '2', action: 'ROUTE_QUEUE', targetQueue: 'SUPPORT_TIER_3' },
      { digit: '3', action: 'TRANSFER_SIP', targetSipUri: 'sip:billing_80@easychat.io' },
      { digit: '9', action: 'AI_BOT_ESCALATION', targetBotWorkflowId: 'bot_rag_triage_80' },
    ],
    fallbackTimeoutSeconds: 15,
    businessHoursSchedule: 'MON_FRI_0800_2000_EST',
    isRecordingMandatory: true,
  },
];
