export interface MockCpqPriceBookEntry {
  skuId: string;
  productName: string;
  category: 'SEAT_LICENSE' | 'ADD_ON_VOIP' | 'ADD_ON_AI_COPILOT' | 'PROFESSIONAL_SERVICES' | 'DEDICATED_INFRASTRUCTURE';
  listPriceMonthlyUsd: number;
  annualCommitmentDiscountPercent: number;
  minSeatCommitment: number;
  maxSeatVolume: number;
  isVolumeTierEligible: boolean;
  currencyCode: 'USD';
  taxExemptCategory: boolean;
  effectiveQuarter: string;
}

export const ENTERPRISE_CPQ_PRICE_BOOKS_MATRIX: MockCpqPriceBookEntry[] = [
  {
    skuId: 'SKU-CPQ-0001',
    productName: 'Enterprise SaaS Tier 1 - Module Suite 1',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 65,
    annualCommitmentDiscountPercent: 11,
    minSeatCommitment: 2,
    maxSeatVolume: 100,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0002',
    productName: 'Enterprise SaaS Tier 2 - Module Suite 2',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 80,
    annualCommitmentDiscountPercent: 12,
    minSeatCommitment: 4,
    maxSeatVolume: 200,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0003',
    productName: 'Enterprise SaaS Tier 3 - Module Suite 3',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 95,
    annualCommitmentDiscountPercent: 13,
    minSeatCommitment: 6,
    maxSeatVolume: 300,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0004',
    productName: 'Enterprise SaaS Tier 4 - Module Suite 4',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 110,
    annualCommitmentDiscountPercent: 14,
    minSeatCommitment: 8,
    maxSeatVolume: 400,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0005',
    productName: 'Enterprise SaaS Tier 5 - Module Suite 5',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 125,
    annualCommitmentDiscountPercent: 15,
    minSeatCommitment: 10,
    maxSeatVolume: 500,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0006',
    productName: 'Enterprise SaaS Tier 6 - Module Suite 6',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 140,
    annualCommitmentDiscountPercent: 16,
    minSeatCommitment: 12,
    maxSeatVolume: 600,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0007',
    productName: 'Enterprise SaaS Tier 7 - Module Suite 7',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 155,
    annualCommitmentDiscountPercent: 17,
    minSeatCommitment: 14,
    maxSeatVolume: 700,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0008',
    productName: 'Enterprise SaaS Tier 8 - Module Suite 8',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 170,
    annualCommitmentDiscountPercent: 18,
    minSeatCommitment: 16,
    maxSeatVolume: 800,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0009',
    productName: 'Enterprise SaaS Tier 9 - Module Suite 9',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 185,
    annualCommitmentDiscountPercent: 19,
    minSeatCommitment: 18,
    maxSeatVolume: 900,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0010',
    productName: 'Enterprise SaaS Tier 10 - Module Suite 10',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 200,
    annualCommitmentDiscountPercent: 20,
    minSeatCommitment: 20,
    maxSeatVolume: 1000,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0011',
    productName: 'Enterprise SaaS Tier 11 - Module Suite 11',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 215,
    annualCommitmentDiscountPercent: 21,
    minSeatCommitment: 22,
    maxSeatVolume: 1100,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0012',
    productName: 'Enterprise SaaS Tier 12 - Module Suite 0',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 230,
    annualCommitmentDiscountPercent: 22,
    minSeatCommitment: 24,
    maxSeatVolume: 1200,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0013',
    productName: 'Enterprise SaaS Tier 13 - Module Suite 1',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 245,
    annualCommitmentDiscountPercent: 23,
    minSeatCommitment: 26,
    maxSeatVolume: 1300,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0014',
    productName: 'Enterprise SaaS Tier 14 - Module Suite 2',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 260,
    annualCommitmentDiscountPercent: 24,
    minSeatCommitment: 28,
    maxSeatVolume: 1400,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0015',
    productName: 'Enterprise SaaS Tier 15 - Module Suite 3',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 275,
    annualCommitmentDiscountPercent: 10,
    minSeatCommitment: 30,
    maxSeatVolume: 1500,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0016',
    productName: 'Enterprise SaaS Tier 16 - Module Suite 4',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 290,
    annualCommitmentDiscountPercent: 11,
    minSeatCommitment: 32,
    maxSeatVolume: 1600,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0017',
    productName: 'Enterprise SaaS Tier 17 - Module Suite 5',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 305,
    annualCommitmentDiscountPercent: 12,
    minSeatCommitment: 34,
    maxSeatVolume: 1700,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0018',
    productName: 'Enterprise SaaS Tier 18 - Module Suite 6',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 320,
    annualCommitmentDiscountPercent: 13,
    minSeatCommitment: 36,
    maxSeatVolume: 1800,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0019',
    productName: 'Enterprise SaaS Tier 19 - Module Suite 7',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 335,
    annualCommitmentDiscountPercent: 14,
    minSeatCommitment: 38,
    maxSeatVolume: 1900,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0020',
    productName: 'Enterprise SaaS Tier 20 - Module Suite 8',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 350,
    annualCommitmentDiscountPercent: 15,
    minSeatCommitment: 40,
    maxSeatVolume: 2000,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0021',
    productName: 'Enterprise SaaS Tier 21 - Module Suite 9',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 365,
    annualCommitmentDiscountPercent: 16,
    minSeatCommitment: 42,
    maxSeatVolume: 2100,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0022',
    productName: 'Enterprise SaaS Tier 22 - Module Suite 10',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 380,
    annualCommitmentDiscountPercent: 17,
    minSeatCommitment: 44,
    maxSeatVolume: 2200,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0023',
    productName: 'Enterprise SaaS Tier 23 - Module Suite 11',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 395,
    annualCommitmentDiscountPercent: 18,
    minSeatCommitment: 46,
    maxSeatVolume: 2300,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0024',
    productName: 'Enterprise SaaS Tier 24 - Module Suite 0',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 410,
    annualCommitmentDiscountPercent: 19,
    minSeatCommitment: 48,
    maxSeatVolume: 2400,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0025',
    productName: 'Enterprise SaaS Tier 25 - Module Suite 1',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 425,
    annualCommitmentDiscountPercent: 20,
    minSeatCommitment: 50,
    maxSeatVolume: 2500,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0026',
    productName: 'Enterprise SaaS Tier 26 - Module Suite 2',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 440,
    annualCommitmentDiscountPercent: 21,
    minSeatCommitment: 52,
    maxSeatVolume: 2600,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0027',
    productName: 'Enterprise SaaS Tier 27 - Module Suite 3',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 455,
    annualCommitmentDiscountPercent: 22,
    minSeatCommitment: 54,
    maxSeatVolume: 2700,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0028',
    productName: 'Enterprise SaaS Tier 28 - Module Suite 4',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 470,
    annualCommitmentDiscountPercent: 23,
    minSeatCommitment: 56,
    maxSeatVolume: 2800,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0029',
    productName: 'Enterprise SaaS Tier 29 - Module Suite 5',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 485,
    annualCommitmentDiscountPercent: 24,
    minSeatCommitment: 58,
    maxSeatVolume: 2900,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0030',
    productName: 'Enterprise SaaS Tier 30 - Module Suite 6',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 500,
    annualCommitmentDiscountPercent: 10,
    minSeatCommitment: 60,
    maxSeatVolume: 3000,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0031',
    productName: 'Enterprise SaaS Tier 31 - Module Suite 7',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 515,
    annualCommitmentDiscountPercent: 11,
    minSeatCommitment: 62,
    maxSeatVolume: 3100,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0032',
    productName: 'Enterprise SaaS Tier 32 - Module Suite 8',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 530,
    annualCommitmentDiscountPercent: 12,
    minSeatCommitment: 64,
    maxSeatVolume: 3200,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0033',
    productName: 'Enterprise SaaS Tier 33 - Module Suite 9',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 545,
    annualCommitmentDiscountPercent: 13,
    minSeatCommitment: 66,
    maxSeatVolume: 3300,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0034',
    productName: 'Enterprise SaaS Tier 34 - Module Suite 10',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 560,
    annualCommitmentDiscountPercent: 14,
    minSeatCommitment: 68,
    maxSeatVolume: 3400,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0035',
    productName: 'Enterprise SaaS Tier 35 - Module Suite 11',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 575,
    annualCommitmentDiscountPercent: 15,
    minSeatCommitment: 70,
    maxSeatVolume: 3500,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0036',
    productName: 'Enterprise SaaS Tier 36 - Module Suite 0',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 590,
    annualCommitmentDiscountPercent: 16,
    minSeatCommitment: 72,
    maxSeatVolume: 3600,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0037',
    productName: 'Enterprise SaaS Tier 37 - Module Suite 1',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 605,
    annualCommitmentDiscountPercent: 17,
    minSeatCommitment: 74,
    maxSeatVolume: 3700,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0038',
    productName: 'Enterprise SaaS Tier 38 - Module Suite 2',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 620,
    annualCommitmentDiscountPercent: 18,
    minSeatCommitment: 76,
    maxSeatVolume: 3800,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0039',
    productName: 'Enterprise SaaS Tier 39 - Module Suite 3',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 635,
    annualCommitmentDiscountPercent: 19,
    minSeatCommitment: 78,
    maxSeatVolume: 3900,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0040',
    productName: 'Enterprise SaaS Tier 40 - Module Suite 4',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 650,
    annualCommitmentDiscountPercent: 20,
    minSeatCommitment: 80,
    maxSeatVolume: 4000,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0041',
    productName: 'Enterprise SaaS Tier 41 - Module Suite 5',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 665,
    annualCommitmentDiscountPercent: 21,
    minSeatCommitment: 82,
    maxSeatVolume: 4100,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0042',
    productName: 'Enterprise SaaS Tier 42 - Module Suite 6',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 680,
    annualCommitmentDiscountPercent: 22,
    minSeatCommitment: 84,
    maxSeatVolume: 4200,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0043',
    productName: 'Enterprise SaaS Tier 43 - Module Suite 7',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 695,
    annualCommitmentDiscountPercent: 23,
    minSeatCommitment: 86,
    maxSeatVolume: 4300,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0044',
    productName: 'Enterprise SaaS Tier 44 - Module Suite 8',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 710,
    annualCommitmentDiscountPercent: 24,
    minSeatCommitment: 88,
    maxSeatVolume: 4400,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0045',
    productName: 'Enterprise SaaS Tier 45 - Module Suite 9',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 725,
    annualCommitmentDiscountPercent: 10,
    minSeatCommitment: 90,
    maxSeatVolume: 4500,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0046',
    productName: 'Enterprise SaaS Tier 46 - Module Suite 10',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 740,
    annualCommitmentDiscountPercent: 11,
    minSeatCommitment: 92,
    maxSeatVolume: 4600,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0047',
    productName: 'Enterprise SaaS Tier 47 - Module Suite 11',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 755,
    annualCommitmentDiscountPercent: 12,
    minSeatCommitment: 94,
    maxSeatVolume: 4700,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0048',
    productName: 'Enterprise SaaS Tier 48 - Module Suite 0',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 770,
    annualCommitmentDiscountPercent: 13,
    minSeatCommitment: 96,
    maxSeatVolume: 4800,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0049',
    productName: 'Enterprise SaaS Tier 49 - Module Suite 1',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 785,
    annualCommitmentDiscountPercent: 14,
    minSeatCommitment: 98,
    maxSeatVolume: 4900,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0050',
    productName: 'Enterprise SaaS Tier 50 - Module Suite 2',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 800,
    annualCommitmentDiscountPercent: 15,
    minSeatCommitment: 100,
    maxSeatVolume: 5000,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0051',
    productName: 'Enterprise SaaS Tier 51 - Module Suite 3',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 815,
    annualCommitmentDiscountPercent: 16,
    minSeatCommitment: 102,
    maxSeatVolume: 5100,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0052',
    productName: 'Enterprise SaaS Tier 52 - Module Suite 4',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 830,
    annualCommitmentDiscountPercent: 17,
    minSeatCommitment: 104,
    maxSeatVolume: 5200,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0053',
    productName: 'Enterprise SaaS Tier 53 - Module Suite 5',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 845,
    annualCommitmentDiscountPercent: 18,
    minSeatCommitment: 106,
    maxSeatVolume: 5300,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0054',
    productName: 'Enterprise SaaS Tier 54 - Module Suite 6',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 860,
    annualCommitmentDiscountPercent: 19,
    minSeatCommitment: 108,
    maxSeatVolume: 5400,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0055',
    productName: 'Enterprise SaaS Tier 55 - Module Suite 7',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 875,
    annualCommitmentDiscountPercent: 20,
    minSeatCommitment: 110,
    maxSeatVolume: 5500,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0056',
    productName: 'Enterprise SaaS Tier 56 - Module Suite 8',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 890,
    annualCommitmentDiscountPercent: 21,
    minSeatCommitment: 112,
    maxSeatVolume: 5600,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0057',
    productName: 'Enterprise SaaS Tier 57 - Module Suite 9',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 905,
    annualCommitmentDiscountPercent: 22,
    minSeatCommitment: 114,
    maxSeatVolume: 5700,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0058',
    productName: 'Enterprise SaaS Tier 58 - Module Suite 10',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 920,
    annualCommitmentDiscountPercent: 23,
    minSeatCommitment: 116,
    maxSeatVolume: 5800,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0059',
    productName: 'Enterprise SaaS Tier 59 - Module Suite 11',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 935,
    annualCommitmentDiscountPercent: 24,
    minSeatCommitment: 118,
    maxSeatVolume: 5900,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0060',
    productName: 'Enterprise SaaS Tier 60 - Module Suite 0',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 950,
    annualCommitmentDiscountPercent: 10,
    minSeatCommitment: 120,
    maxSeatVolume: 6000,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0061',
    productName: 'Enterprise SaaS Tier 61 - Module Suite 1',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 965,
    annualCommitmentDiscountPercent: 11,
    minSeatCommitment: 122,
    maxSeatVolume: 6100,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0062',
    productName: 'Enterprise SaaS Tier 62 - Module Suite 2',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 980,
    annualCommitmentDiscountPercent: 12,
    minSeatCommitment: 124,
    maxSeatVolume: 6200,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0063',
    productName: 'Enterprise SaaS Tier 63 - Module Suite 3',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 995,
    annualCommitmentDiscountPercent: 13,
    minSeatCommitment: 126,
    maxSeatVolume: 6300,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0064',
    productName: 'Enterprise SaaS Tier 64 - Module Suite 4',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 1010,
    annualCommitmentDiscountPercent: 14,
    minSeatCommitment: 128,
    maxSeatVolume: 6400,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0065',
    productName: 'Enterprise SaaS Tier 65 - Module Suite 5',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 1025,
    annualCommitmentDiscountPercent: 15,
    minSeatCommitment: 130,
    maxSeatVolume: 6500,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0066',
    productName: 'Enterprise SaaS Tier 66 - Module Suite 6',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 1040,
    annualCommitmentDiscountPercent: 16,
    minSeatCommitment: 132,
    maxSeatVolume: 6600,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0067',
    productName: 'Enterprise SaaS Tier 67 - Module Suite 7',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 1055,
    annualCommitmentDiscountPercent: 17,
    minSeatCommitment: 134,
    maxSeatVolume: 6700,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0068',
    productName: 'Enterprise SaaS Tier 68 - Module Suite 8',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 1070,
    annualCommitmentDiscountPercent: 18,
    minSeatCommitment: 136,
    maxSeatVolume: 6800,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0069',
    productName: 'Enterprise SaaS Tier 69 - Module Suite 9',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 1085,
    annualCommitmentDiscountPercent: 19,
    minSeatCommitment: 138,
    maxSeatVolume: 6900,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0070',
    productName: 'Enterprise SaaS Tier 70 - Module Suite 10',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 1100,
    annualCommitmentDiscountPercent: 20,
    minSeatCommitment: 140,
    maxSeatVolume: 7000,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0071',
    productName: 'Enterprise SaaS Tier 71 - Module Suite 11',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 1115,
    annualCommitmentDiscountPercent: 21,
    minSeatCommitment: 142,
    maxSeatVolume: 7100,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0072',
    productName: 'Enterprise SaaS Tier 72 - Module Suite 0',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 1130,
    annualCommitmentDiscountPercent: 22,
    minSeatCommitment: 144,
    maxSeatVolume: 7200,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0073',
    productName: 'Enterprise SaaS Tier 73 - Module Suite 1',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 1145,
    annualCommitmentDiscountPercent: 23,
    minSeatCommitment: 146,
    maxSeatVolume: 7300,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0074',
    productName: 'Enterprise SaaS Tier 74 - Module Suite 2',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 1160,
    annualCommitmentDiscountPercent: 24,
    minSeatCommitment: 148,
    maxSeatVolume: 7400,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0075',
    productName: 'Enterprise SaaS Tier 75 - Module Suite 3',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 1175,
    annualCommitmentDiscountPercent: 10,
    minSeatCommitment: 150,
    maxSeatVolume: 7500,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0076',
    productName: 'Enterprise SaaS Tier 76 - Module Suite 4',
    category: 'ADD_ON_VOIP',
    listPriceMonthlyUsd: 1190,
    annualCommitmentDiscountPercent: 11,
    minSeatCommitment: 152,
    maxSeatVolume: 7600,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0077',
    productName: 'Enterprise SaaS Tier 77 - Module Suite 5',
    category: 'ADD_ON_AI_COPILOT',
    listPriceMonthlyUsd: 1205,
    annualCommitmentDiscountPercent: 12,
    minSeatCommitment: 154,
    maxSeatVolume: 7700,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0078',
    productName: 'Enterprise SaaS Tier 78 - Module Suite 6',
    category: 'PROFESSIONAL_SERVICES',
    listPriceMonthlyUsd: 1220,
    annualCommitmentDiscountPercent: 13,
    minSeatCommitment: 156,
    maxSeatVolume: 7800,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0079',
    productName: 'Enterprise SaaS Tier 79 - Module Suite 7',
    category: 'DEDICATED_INFRASTRUCTURE',
    listPriceMonthlyUsd: 1235,
    annualCommitmentDiscountPercent: 14,
    minSeatCommitment: 158,
    maxSeatVolume: 7900,
    isVolumeTierEligible: false,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
  {
    skuId: 'SKU-CPQ-0080',
    productName: 'Enterprise SaaS Tier 80 - Module Suite 8',
    category: 'SEAT_LICENSE',
    listPriceMonthlyUsd: 1250,
    annualCommitmentDiscountPercent: 15,
    minSeatCommitment: 160,
    maxSeatVolume: 8000,
    isVolumeTierEligible: true,
    currencyCode: 'USD',
    taxExemptCategory: false,
    effectiveQuarter: 'FY2026-Q3',
  },
];
