export interface MockOmniRouteEntry {
  ruleId: string;
  channelType: 'WEB_CHAT' | 'WHATSAPP' | 'VOICE_PSTN' | 'SMS' | 'EMAIL_INBOUND';
  priorityScore: number;
  conditionLogic: string;
  skillRequirements: string[];
  agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST' | 'LEAST_ACTIVE_CONVERSATIONS' | 'WEIGHTED_SKILL_AFFINITY';
  escalationThresholdSeconds: number;
  activeStatus: boolean;
}

export const ENTERPRISE_OMNICHANNEL_ROUTING_TREES: MockOmniRouteEntry[] = [
  {
    ruleId: 'route_omni_0001',
    channelType: 'WHATSAPP',
    priorityScore: 99,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_1',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 65,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0002',
    channelType: 'VOICE_PSTN',
    priorityScore: 98,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_2',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 70,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0003',
    channelType: 'SMS',
    priorityScore: 97,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_3',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 75,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0004',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 96,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_4',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 80,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0005',
    channelType: 'WEB_CHAT',
    priorityScore: 95,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_5',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 85,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0006',
    channelType: 'WHATSAPP',
    priorityScore: 94,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_6',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 90,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0007',
    channelType: 'VOICE_PSTN',
    priorityScore: 93,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_7',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 95,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0008',
    channelType: 'SMS',
    priorityScore: 92,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_8',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 100,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0009',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 91,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_9',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 105,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0010',
    channelType: 'WEB_CHAT',
    priorityScore: 90,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_10',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 110,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0011',
    channelType: 'WHATSAPP',
    priorityScore: 89,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_11',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 115,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0012',
    channelType: 'VOICE_PSTN',
    priorityScore: 88,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_12',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 120,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0013',
    channelType: 'SMS',
    priorityScore: 87,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_13',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 125,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0014',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 86,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_14',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 130,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0015',
    channelType: 'WEB_CHAT',
    priorityScore: 85,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_15',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 135,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0016',
    channelType: 'WHATSAPP',
    priorityScore: 84,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_16',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 140,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0017',
    channelType: 'VOICE_PSTN',
    priorityScore: 83,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_17',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 145,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0018',
    channelType: 'SMS',
    priorityScore: 82,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_18',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 150,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0019',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 81,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_19',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 155,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0020',
    channelType: 'WEB_CHAT',
    priorityScore: 100,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_20',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 160,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0021',
    channelType: 'WHATSAPP',
    priorityScore: 99,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_21',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 165,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0022',
    channelType: 'VOICE_PSTN',
    priorityScore: 98,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_22',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 170,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0023',
    channelType: 'SMS',
    priorityScore: 97,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_23',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 175,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0024',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 96,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_24',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 180,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0025',
    channelType: 'WEB_CHAT',
    priorityScore: 95,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_25',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 185,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0026',
    channelType: 'WHATSAPP',
    priorityScore: 94,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_26',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 190,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0027',
    channelType: 'VOICE_PSTN',
    priorityScore: 93,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_27',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 195,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0028',
    channelType: 'SMS',
    priorityScore: 92,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_28',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 200,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0029',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 91,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_29',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 205,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0030',
    channelType: 'WEB_CHAT',
    priorityScore: 90,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_30',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 210,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0031',
    channelType: 'WHATSAPP',
    priorityScore: 89,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_31',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 215,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0032',
    channelType: 'VOICE_PSTN',
    priorityScore: 88,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_32',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 220,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0033',
    channelType: 'SMS',
    priorityScore: 87,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_33',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 225,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0034',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 86,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_34',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 230,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0035',
    channelType: 'WEB_CHAT',
    priorityScore: 85,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_35',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 235,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0036',
    channelType: 'WHATSAPP',
    priorityScore: 84,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_36',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 240,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0037',
    channelType: 'VOICE_PSTN',
    priorityScore: 83,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_37',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 245,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0038',
    channelType: 'SMS',
    priorityScore: 82,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_38',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 250,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0039',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 81,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_39',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 255,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0040',
    channelType: 'WEB_CHAT',
    priorityScore: 100,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_40',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 260,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0041',
    channelType: 'WHATSAPP',
    priorityScore: 99,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_41',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 265,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0042',
    channelType: 'VOICE_PSTN',
    priorityScore: 98,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_42',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 270,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0043',
    channelType: 'SMS',
    priorityScore: 97,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_43',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 275,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0044',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 96,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_44',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 280,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0045',
    channelType: 'WEB_CHAT',
    priorityScore: 95,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_45',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 285,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0046',
    channelType: 'WHATSAPP',
    priorityScore: 94,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_46',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 290,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0047',
    channelType: 'VOICE_PSTN',
    priorityScore: 93,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_47',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 295,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0048',
    channelType: 'SMS',
    priorityScore: 92,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_48',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 300,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0049',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 91,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_49',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 305,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0050',
    channelType: 'WEB_CHAT',
    priorityScore: 90,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_50',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 310,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0051',
    channelType: 'WHATSAPP',
    priorityScore: 89,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_51',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 315,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0052',
    channelType: 'VOICE_PSTN',
    priorityScore: 88,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_52',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 320,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0053',
    channelType: 'SMS',
    priorityScore: 87,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_53',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 325,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0054',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 86,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_54',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 330,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0055',
    channelType: 'WEB_CHAT',
    priorityScore: 85,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_55',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 335,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0056',
    channelType: 'WHATSAPP',
    priorityScore: 84,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_56',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 340,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0057',
    channelType: 'VOICE_PSTN',
    priorityScore: 83,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_57',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 345,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0058',
    channelType: 'SMS',
    priorityScore: 82,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_58',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 350,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0059',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 81,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_59',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 355,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0060',
    channelType: 'WEB_CHAT',
    priorityScore: 100,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_60',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 360,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0061',
    channelType: 'WHATSAPP',
    priorityScore: 99,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_61',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 365,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0062',
    channelType: 'VOICE_PSTN',
    priorityScore: 98,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_62',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 370,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0063',
    channelType: 'SMS',
    priorityScore: 97,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_63',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 375,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0064',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 96,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_64',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 380,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0065',
    channelType: 'WEB_CHAT',
    priorityScore: 95,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_65',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 385,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0066',
    channelType: 'WHATSAPP',
    priorityScore: 94,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_66',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 390,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0067',
    channelType: 'VOICE_PSTN',
    priorityScore: 93,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_67',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 395,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0068',
    channelType: 'SMS',
    priorityScore: 92,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_68',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 400,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0069',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 91,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_69',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 405,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0070',
    channelType: 'WEB_CHAT',
    priorityScore: 90,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_70',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 410,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0071',
    channelType: 'WHATSAPP',
    priorityScore: 89,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_71',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 415,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0072',
    channelType: 'VOICE_PSTN',
    priorityScore: 88,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_72',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 420,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0073',
    channelType: 'SMS',
    priorityScore: 87,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_73',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 425,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0074',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 86,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_74',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 430,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0075',
    channelType: 'WEB_CHAT',
    priorityScore: 85,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_75',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 435,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0076',
    channelType: 'WHATSAPP',
    priorityScore: 84,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_76',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 440,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0077',
    channelType: 'VOICE_PSTN',
    priorityScore: 83,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_77',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_2', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 445,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0078',
    channelType: 'SMS',
    priorityScore: 82,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_78',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_3', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'ROUND_ROBIN_IDLE_LONGEST',
    escalationThresholdSeconds: 450,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0079',
    channelType: 'EMAIL_INBOUND',
    priorityScore: 81,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_79',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_4', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'LEAST_ACTIVE_CONVERSATIONS',
    escalationThresholdSeconds: 455,
    activeStatus: true,
  },
  {
    ruleId: 'route_omni_0080',
    channelType: 'WEB_CHAT',
    priorityScore: 100,
    conditionLogic: 'JSON_SCHEMA_LOGIC_EXPRESSION_80',
    skillRequirements: ['ENGLISH_C2', 'FINANCIAL_ACCOUNTS_TIER_1', 'ENTERPRISE_SLA_URGENT'],
    agentRoutingStrategy: 'WEIGHTED_SKILL_AFFINITY',
    escalationThresholdSeconds: 460,
    activeStatus: true,
  },
];
